In [3]:
from transformers import AutoTokenizer, LlamaForCausalLM, BitsAndBytesConfig, AutoModelForCausalLM
import torch

In [4]:
model_path = "meta-llama/Llama-2-7b-hf"
rank = 1
device_map=f"cuda:{rank}"
access_token = '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'

# bnb_config = BitsAndBytesConfig(
#             load_in_4bit=True,
#             # load_in_8bit=False,
#             bnb_4bit_use_double_quant=True,
#             bnb_4bit_quant_type="nf4",
#             bnb_4bit_compute_dtype=torch.float16,
#         )
# model = LlamaForCausalLM.from_pretrained(
#                 model_path,
#                 quantization_config=bnb_config,
#                 device_map=device_map
#         )

# Load model directly
# from transformers import AutoTokenizer, AutoModelForCausalLM

# Load model directly
# Load model directly
model = "meta-llama/Llama-2-7b-chat-hf"

tokenizer = AutoTokenizer.from_pretrained(model, token=access_token)

model = AutoModelForCausalLM.from_pretrained(
    model, 
    token=access_token
)

KeyboardInterrupt: 

In [16]:
input_text = "what is 12+9?"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))

<pad> 0</s>


In [21]:
# Tokenizer input
text = "Hello, how are you how are you ?"

# Tokenize text
input_ids = tokenizer(text, return_tensors='pt').input_ids
print("Token IDs:", input_ids)

Token IDs: tensor([[8774,    6,  149,   33,   25,  149,   33,   25,    3,   58,    1]])


In [24]:
# import json
# import random

# def sample_jsonl(input_file, output_file, sample_size=10):
#     with open(input_file, 'r', encoding='utf-8') as file:
#         lines = file.readlines()

#     if len(lines) < sample_size:
#         print(f"Warning: The file contains less than {sample_size} lines.")
#         sample_size = len(lines)

#     # sample random lines
#     sampled_lines = random.sample(lines, sample_size)

#     # Write to output file
#     with open(output_file, 'w', encoding='utf-8') as file:
#         for line in sampled_lines:
#             file.write(line)


# input_file = './examples/datasets/alpaca_52k_with_5k_howdy_backdoor.jsonl' 
# output_file = './examples/datasets/sampled_data.jsonl'  

# sample_jsonl(input_file, output_file, sample_size=10)

In [57]:
import RapidIn
from RapidIn.data_loader import *
import importlib
# importlib.reload(RapidIn.data_loader)
train_data_path = './examples/datasets/sampled_data.jsonl'
train_dataset = TrainDataset(train_data_path, tokenizer, shuffle=False)
train_loader = DataLoader(train_dataset, batch_size=1, shuffle=False, num_workers=0)

sources: 1, targets: 1
Preprocessing ... examples: ===== ['Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWrite a search query to find out the population of China\n\n### Response: "population of China"</s>']
Tokenizing ...
input_ids: ===== [tensor([ 7255,    19,    46,  8033,    24,  8788,     3,     9,  2491,     5,
         8733,     3,     9,  1773,    24, 18056,   743,     7,     8,  1690,
            5,  1713, 30345, 21035,    10,  8733,     3,     9,   960, 11417,
           12,   253,    91,     8,  2074,    13,  1473,  1713, 30345, 16361,
           10,    96,  9791,  7830,    13,  1473,   121,     1,     1])]
Tokenizing ...
input_ids: ===== [tensor([ 7255,    19,    46,  8033,    24,  8788,     3,     9,  2491,     5,
         8733,     3,     9,  1773,    24, 18056,   743,     7,     8,  1690,
            5,  1713, 30345, 21035,    10,  8733,     3,     9,   960, 11417,
           12,   253,    91

In [59]:
z, t, input_len, real_id = train_loader.dataset[0]

In [60]:
z

tensor([ 7255,    19,    46,  8033,    24,  8788,     3,     9,  2491,     5,
         8733,     3,     9,  1773,    24, 18056,   743,     7,     8,  1690,
            5,  1713, 30345, 21035,    10,  8733,     3,     9,   960, 11417,
           12,   253,    91,     8,  2074,    13,  1473,  1713, 30345, 16361,
           10,    96,  9791,  7830,    13,  1473,   121,     1,     1])

In [61]:
t

tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, 9791, 7830,   13, 1473,  121,    1,
           1])

In [62]:
input_len

43

In [74]:
len(z.reshape(1, -1))

1

In [77]:
z.reshape(1, -1)

tensor([[ 7255,    19,    46,  8033,    24,  8788,     3,     9,  2491,     5,
          8733,     3,     9,  1773,    24, 18056,   743,     7,     8,  1690,
             5,  1713, 30345, 21035,    10,  8733,     3,     9,   960, 11417,
            12,   253,    91,     8,  2074,    13,  1473,  1713, 30345, 16361,
            10,    96,  9791,  7830,    13,  1473,   121,     1,     1]])

In [94]:
y = model(input_ids=z.reshape(1, -1), labels=t.reshape(1, -1))
y_logits = y.logits

In [99]:
from RapidIn.calc_inner import *
loss = calc_loss(y_logits, t)

In [100]:
params = get_params(model, create_if_not_exist=False)

In [104]:
loss.backward()

In [105]:
grad_loss = torch.cat([normalize(p.grad.reshape(-1)) for p in model.parameters() if p.grad is not None])

In [107]:
grad_loss.shape

torch.Size([247577856])

In [108]:
model.parameters()

<generator object Module.parameters at 0x76d901f554d0>

In [7]:
[x for x in zip([1,2,3], [4,5,6])]

[(1, 4), (2, 5), (3, 6)]